import type { Metadata } from 'next';
import { Alfa_Slab_One, Oswald } from 'next/font/google';
import { Providers } from './providers';
import { Navbar } from './components/Nav';
import './globals.css';

const inter = Alfa_Slab_One({ weight: ['400'], subsets: ['latin'] });
export const oswald = Oswald({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Technical Club',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="light">
			<body className={inter.className}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
